/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LawGeneratorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  lawDirectory: "\uB300\uD55C\uBBFC\uAD6D \uBC95\uB960",
  templatesDirectory: "Templates"
};
var LawGeneratorPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "create-new-law",
      name: "\uC0C8 \uBC95\uB839 \uB9CC\uB4E4\uAE30",
      callback: () => {
        new LawInputDialog(this.app, async (lawName) => {
          await this.generateLawFiles(lawName);
        }).open();
      }
    });
    this.addRibbonIcon("document", "\uC0C8 \uBC95\uB839 \uB9CC\uB4E4\uAE30", (evt) => {
      new LawInputDialog(this.app, async (lawName) => {
        await this.generateLawFiles(lawName);
      }).open();
    });
    this.addSettingTab(new LawGeneratorSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // 핵심 엔진: 폴더 트리 및 파일 3개(+README) 생성 로직
  async generateLawFiles(lawName) {
    const { vault } = this.app;
    const baseDir = this.settings.lawDirectory;
    const templatesDir = this.settings.templatesDirectory;
    const targetFolderPath = `${baseDir}/${lawName}`;
    try {
      await this.ensureFolderExists(targetFolderPath);
      const filesToCreate = [
        { fileName: "README.md", templateName: "README Template.md" },
        { fileName: "\uBC95\uB960.md", templateName: "\uBC95\uB960 Template.md" },
        { fileName: "\uC2DC\uD589\uB839.md", templateName: "\uC2DC\uD589\uB839 Template.md" },
        { fileName: "\uC2DC\uD589\uADDC\uCE59.md", templateName: "\uC2DC\uD589\uADDC\uCE59 Template.md" }
      ];
      for (const file of filesToCreate) {
        const filePath = `${targetFolderPath}/${file.fileName}`;
        const fileExists = vault.getAbstractFileByPath(filePath);
        if (fileExists) {
          continue;
        }
        const templatePath = `${templatesDir}/${file.templateName}`;
        let fileContent = "";
        try {
          const templateFile = vault.getAbstractFileByPath(templatePath);
          if (templateFile && "read" in templateFile) {
            const rawContent = await vault.read(templateFile);
            fileContent = rawContent.replace(/\{\{VALUE:법령명\}\}/g, lawName);
          } else {
            if (file.fileName === "README.md") {
              fileContent = `# ${lawName}

## \uBC95\uB839
-[[\uBC95\uB960]]
-[[\uC2DC\uD589\uB839]]
-[[\uC2DC\uD589\uADDC\uCE59]]`;
            } else {
              fileContent = `# ${lawName} ${file.fileName.replace(".md", "")}

\uC5EC\uAE30\uC5D0 \uB0B4\uC6A9\uC744 \uC785\uB825\uD558\uC138\uC694.`;
            }
          }
        } catch (err) {
          new import_obsidian.Notice(`\uD15C\uD50C\uB9BF \uC77D\uAE30 \uC2E4\uD328: ${file.templateName}. \uAE30\uBCF8 \uB0B4\uC6A9\uC73C\uB85C \uC0DD\uC131\uD569\uB2C8\uB2E4.`);
        }
        await vault.create(filePath, fileContent);
      }
      new import_obsidian.Notice(`\u{1F389} '${lawName}' \uBC95\uB839 \uD3F4\uB354 \uBC0F 3\uB2E8 \uD30C\uC77C\uC774 \uC131\uACF5\uC801\uC73C\uB85C \uC0DD\uC131\uB418\uC5C8\uC2B5\uB2C8\uB2E4!`);
    } catch (error) {
      console.error(error);
      new import_obsidian.Notice(`\u274C \uC0DD\uC131 \uC2E4\uD328: ${error.message}`);
    }
  }
  // 폴더 존재 여부 확인 후 없으면 순차 생성하는 헬퍼 함수
  async ensureFolderExists(path) {
    const { vault } = this.app;
    const parts = path.split("/");
    let currentPath = "";
    for (const part of parts) {
      if (!part) continue;
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const folder = vault.getAbstractFileByPath(currentPath);
      if (!folder) {
        await vault.createFolder(currentPath);
      }
    }
  }
};
var LawInputDialog = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\uC0C8 \uBC95\uB839 \uD30C\uC77C \uC0DD\uC131" });
    let lawName = "";
    new import_obsidian.Setting(contentEl).setName("\uBC95\uB839\uBA85 \uC785\uB825").setDesc("\uC0DD\uC131\uD558\uACE0\uC790 \uD558\uB294 \uBC95\uB839\uC758 \uC774\uB984\uC744 \uC785\uB825\uD558\uC138\uC694 (\uC608: \uBBFC\uBC95, \uADFC\uB85C\uAE30\uC900\uBC95)").addText(
      (text) => text.onChange((value) => {
        lawName = value;
      })
    );
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("\uC0DD\uC131\uD558\uAE30").setCta().onClick(() => {
        if (!lawName.trim()) {
          new import_obsidian.Notice("\u26A0\uFE0F \uBC95\uB839\uBA85\uC744 \uC785\uB825\uD574 \uC8FC\uC138\uC694!");
          return;
        }
        this.close();
        this.onSubmit(lawName.trim());
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var LawGeneratorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Law Generator \uC124\uC815" });
    new import_obsidian.Setting(containerEl).setName("\uBC95\uB839 \uC800\uC7A5 \uD3F4\uB354 \uACBD\uB85C").setDesc("\uC0DD\uC131\uB41C \uBC95\uB839 \uD3F4\uB354\uB4E4\uC774 \uC800\uC7A5\uB420 \uCD5C\uC0C1\uC704 \uACBD\uB85C\uC785\uB2C8\uB2E4.").addText(
      (text) => text.setPlaceholder("\uB300\uD55C\uBBFC\uAD6D \uBC95\uB960").setValue(this.plugin.settings.lawDirectory).onChange(async (value) => {
        this.plugin.settings.lawDirectory = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\uD15C\uD50C\uB9BF \uD3F4\uB354 \uACBD\uB85C").setDesc("\uD15C\uD50C\uB9BF \uD30C\uC77C(README, \uBC95\uB960, \uC2DC\uD589\uB839, \uC2DC\uD589\uADDC\uCE59 Template.md)\uB4E4\uC774 \uC704\uCE58\uD55C \uD3F4\uB354\uC785\uB2C8\uB2E4.").addText(
      (text) => text.setPlaceholder("Templates").setValue(this.plugin.settings.templatesDirectory).onChange(async (value) => {
        this.plugin.settings.templatesDirectory = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
